# Generated by Django 5.2.4 on 2026-01-07 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_with',
            field=models.ManyToManyField(related_name='expenses_shared', through='expenses.ExpenseSplit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
