# Generated by Django 5.2.4 on 2026-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_split_with_expensesplit_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='waiting_for_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
