# Generated by Django 5.2.4 on 2026-01-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensesplit_waiting_for_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
