# Generated by Django 5.2.4 on 2026-01-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensesplit_created_at_expensesplit_read_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesplit',
            old_name='read_status',
            new_name='is_viewed_by_creator',
        ),
    ]
