# Generated by Django 5.2.4 on 2026-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_read_status_expensesplit_is_viewed_by_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
